version: '3.8'

services:
  nginx:
    image: nginx:alpine
    restart: always

    ports:
      - "8280:80"

    volumes:
      # hasil build React dari Jenkins
      - /app/projects/portofolio/build:/usr/share/nginx/html

      # config nginx
      - /app/projects/portofolio/nginx/default.conf:/etc/nginx/conf.d/default.conf