pipeline {
    agent { label 'react-js' }

    environment {
        APP_NAME  = "portofolio"
        APP_DIR   = "/app/projects/portofolio"
        DOCKER_DIR = "/app/projects/portofolio/docker"
    }

    stages {

        stage('Pull Latest Code') {
            steps {
                dir("${APP_DIR}") {
                    sh "git config --global --add safe.directory ${APP_DIR}"
                    checkout scm
                }
            }
        }

        stage('Install Dependencies') {
            steps {
                dir("${APP_DIR}") {
                    sh 'npm ci --prefer-offline --no-audit'
                }
            }
        }

        stage('Build React App') {
            steps {
                dir("${APP_DIR}") {
                    sh 'NODE_OPTIONS="--max-old-space-size=512" npm run build'
                }
            }
        }

        stage('Deploy Container') {
            steps {
                dir("${DOCKER_DIR}") {
                    sh """
                        docker compose -p ${APP_NAME} up -d --build
                    """
                }
            }
        }
    }
}